apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: simpleappapi
  name: simpleappapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simpleappapi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: simpleappapi
    spec:
      hostname: simpleappapi
      containers:
      - image: mfaksacr.azurecr.io/testapi:v1
        name: testapi
        ports:
        - containerPort: 80
        resources: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: simpleapp
  name: simpleapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simpleapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: simpleapp
    spec:
      containers:
        - name: testmvc2
          image: mfaksacr.azurecr.io/testmvc:v2
          ports:
            - containerPort: 80
            - containerPort: 443
          resources: {}
          env:
            - name: TestApiServerHost
              value: "simpleappapi"
            - name: TestApiServerPort
              value: "80"
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: simpleapp
  name: simpleapp
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
  selector:
    app: simpleapp
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: simpleappapi
  name: simpleappapi
spec:
  clusterIP: None
  ports:
  - port: 80
    name: http
  selector:
    app: simpleappapi
status:
  loadBalancer: {}
